# Generated by Django 5.1.5 on 2025-02-03 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general_proccess', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacherinfo',
            fields=[
                ('teacher_id', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True, verbose_name='کد شش رقم معلم')),
                ('teacher_name', models.CharField(max_length=50, verbose_name='نام معلم')),
                ('teacher_last_name', models.CharField(max_length=70, verbose_name='نام خانوادگی معلم')),
                ('teacher_phone_number', models.IntegerField(verbose_name='شماره تلفن')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentinfo')),
                ('teacher_book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='general_proccess.book')),
                ('teacher_field', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='general_proccess.field')),
                ('teacher_grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='general_proccess.grade')),
            ],
        ),
    ]
