# Generated by Django 5.1.5 on 2025-02-01 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacherinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=50, verbose_name='نام')),
                ('teacher_last_name', models.CharField(max_length=70, verbose_name='فامیلی')),
                ('teacher_phone_number', models.IntegerField(max_length=40, verbose_name='شماره تلفن')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentinfo')),
            ],
        ),
    ]
