# Generated by Django 5.1.5 on 2025-02-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherinfo',
            name='teacher_last_name',
            field=models.CharField(max_length=70, verbose_name='نام خانوادگی معلم'),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='teacher_name',
            field=models.CharField(max_length=50, verbose_name='نام معلم'),
        ),
    ]
