# Generated by Django 5.1.5 on 2025-02-02 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_alter_teacherinfo_teacher_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherinfo',
            name='teacher_book',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='teahcer_grade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
