# Generated by Django 5.1.5 on 2025-02-03 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general_proccess', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studentinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frist_name', models.CharField(max_length=50, verbose_name='نام دانش اموز')),
                ('last_name', models.CharField(max_length=70, verbose_name='نام خانوادگی دانش اموز')),
                ('phone_number', models.IntegerField(verbose_name='شماره تلفن')),
                ('student_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_proccess.book')),
                ('student_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_proccess.field')),
                ('student_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_proccess.grade')),
            ],
        ),
    ]
