# Generated by Django 5.1.5 on 2025-02-03 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='student_book',
        ),
    ]
