# Generated by Django 5.1.5 on 2025-02-03 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=70, verbose_name='نام رشته')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=50, verbose_name='پایه تحصیلی')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=70, verbose_name='نام کتاب')),
                ('book_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_proccess.field')),
                ('book_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_proccess.grade')),
            ],
        ),
    ]
