# Generated by Django 5.1.5 on 2025-02-01 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0003_alter_studentinfo_phone_number'),
        ('teachers', '0003_alter_teacherinfo_teacher_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تقویم')),
                ('is_present', models.BooleanField(default=False, verbose_name='حاضر یا غایب')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='روز کلاس')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='students.studentinfo', verbose_name='نام دانش اموز')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='teachers.teacherinfo', verbose_name='نام معلم')),
            ],
        ),
    ]
