# Generated by Django 5.1.5 on 2025-02-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studentinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frist_name', models.CharField(max_length=50, verbose_name='نام')),
                ('last_name', models.CharField(max_length=70, verbose_name='فامیلی')),
                ('phone_number', models.IntegerField(max_length=40, verbose_name='شماره تلفن')),
            ],
        ),
    ]
