# Generated by Django 5.1.5 on 2025-02-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='frist_name',
            field=models.CharField(max_length=50, verbose_name='نام دانش اموز'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='last_name',
            field=models.CharField(max_length=70, verbose_name='نام خانوادگی دانش اموز'),
        ),
    ]
