# Generated by Django 5.1.5 on 2025-02-01 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_studentinfo_frist_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='phone_number',
            field=models.IntegerField(verbose_name='شماره تلفن'),
        ),
    ]
