# Generated by Django 5.1.5 on 2025-02-02 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_studentinfo_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='field',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='grade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
